# SITE CONFIGURATION
title: site dige # your site title
author: mirzakhaniali # You :P
description: > # Meta description of Homepage
 بیایید درس بخوانیم 
baseurl: "/labexam" # the subpath of your site, e.g. /blog
url: "https://mirzakhaniali.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: aliam
  links:
    - https://twitter.com/nistke
    - https://www.facebook.com/facebookamkenist
    - https://www.linkedin.com/in/nadaram
    - https://plus.google.com/invojdananta_hala_nashnidam
    - https://github.com/yadamnist
    - https://keybase.io/chie_ina_vojdanan

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'calendar', link: '/cal'}
  - {name: 'ertebat', link: '/contact'}

tagline: >
  inja mal mane

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mirzakhania94@gmail.com # email for form submission

twitter_username: beststudent # replace with your_twitter_username or comment to remove link from footer
github_username:  khodam # replace with your_github_username or comment to remove link from footer
instagram_username: salam # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: ostad_gheraati_:) # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
